# Generated by Django 4.1.4 on 2023-01-10 10:40

from django.db import migrations, models
import restaurant.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_alter_ingredient_metric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='metric',
            field=models.CharField(choices=[('KG', 'kg'), ('L', 'l'), ('UNITS', 'units')], default='KG', max_length=6),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=restaurant.models.NameField(max_length=50),
        ),
    ]
