# Generated by Django 4.1.4 on 2023-01-12 11:39

from django.db import migrations
import restaurant.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_alter_ingredient_metric_alter_ingredient_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='menu_item_id',
        ),
        migrations.AddField(
            model_name='purchase',
            name='menu_item_name',
            field=restaurant.models.NameField(default='cheese', max_length=50),
            preserve_default=False,
        ),
    ]
