# Generated by Django 4.1.4 on 2023-01-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_remove_purchase_menu_item_id_purchase_menu_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity_available',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
