# Generated by Django 4.1.4 on 2023-01-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_ingredient_metric'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('name',), name='ingredient_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='reciperequirement',
            constraint=models.UniqueConstraint(fields=('ingredient_id', 'menu_item_id'), name='menu_item_ingredient_unique'),
        ),
    ]
