# Generated by Django 4.1.4 on 2023-01-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_ingredient_ingredient_name_unique_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_menu_items'),
        ),
    ]
