# Generated by Django 4.1.4 on 2023-01-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_menuitem_unique_menu_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='bill',
            new_name='revenue',
        ),
        migrations.AddField(
            model_name='purchase',
            name='cost',
            field=models.FloatField(default=0),
        ),
    ]
