# Generated by Django 4.1.4 on 2023-01-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_rename_bill_purchase_revenue_purchase_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='quantity_purchased',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='metric',
            field=models.CharField(choices=[('KG', 'g'), ('ML', 'ml'), ('UNITS', 'units')], default='KG', max_length=6),
        ),
    ]
