# Generated by Django 4.1.4 on 2023-01-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_purchase_quantity_purchased_alter_ingredient_metric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='metric',
            field=models.CharField(choices=[('KG', 'g'), ('L', 'l'), ('UNITS', 'units')], default='KG', max_length=6),
        ),
    ]
